name = "SpectralKernels"
uuid = "268f51b4-14a7-497b-8c0c-7b947140b648"
version = "0.1.0"
authors = ["Chris Geoga <geoga@wisc.edu>", "Paul Beckman <paul.beckman@cims.nyu.edu>"]

[deps]
Bessels = "0e736298-9ec6-45e8-9647-e4fc86a2fe38"
FINUFFT = "d8beea63-0952-562e-9c6a-8e8ef7364055"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
FastHankelTransform = "3a9aa71a-4826-43c7-bf6d-7fc63822c18e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[weakdeps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
FastHankelTransform = "0.1.1"
