[deps]
Arblib = "fb37089c-8514-4489-9461-98f9c8763369"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BesselK = "432ab697-7a72-484f-bc4a-bc531f5c819b"
Bessels = "0e736298-9ec6-45e8-9647-e4fc86a2fe38"
FINUFFT = "d8beea63-0952-562e-9c6a-8e8ef7364055"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GPMaxlik = "988d40dc-a58a-4803-bd2c-6d7438fe27fe"
GSL = "92c85e6c-cbff-5e0c-80f7-495c94daaecd"
HypergeometricFunctions = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
Memoization = "6fafb56a-5788-4b4e-91ca-c0cea6611c73"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Vecchia = "8d73829f-f4b0-474a-9580-cecc8e084068"
