[deps]
BesselK = "432ab697-7a72-484f-bc4a-bc531f5c819b"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
HypergeometricFunctions = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
SpectralKernels = "268f51b4-14a7-497b-8c0c-7b947140b648"
